user:
  create: true
  email: ${sentry_root_user_email}
  password: ${sentry_root_user_password}

nginx:
  enabled: false

rabbitmq:
  enabled: false

sentry:
  existingSecret: ${existing_secret_name}
  existingSecretKey: sentry_secret_key
  web:
    service:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /_health/
        alb.ingress.kubernetes.io/healthcheck-port: traffic-port

relay:
  mode: proxy
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /api/relay/healthcheck/ready/
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port

ingress:
  enabled: false

postgresql:
  enabled: false

externalPostgresql:
  host: ${postgres_db_host}
  port: ${postgres_db_port}
  database: ${postgres_db_name}
  username: ${postgres_username}
  password: "${postgres_password}"

%{ if smtp_enable == true ~}
mail:
  backend: smtp
  useTls: true
  from: ${sentry_root_user_email}
  host: ${smtp_host}
  port: 587
  username: ${smtp_username}
  password: ${smtp_password}
%{ endif ~}

system:
  url: "https://${dns_name}"
  adminEmail: "${sentry_root_user_email}"
  public: false

%{ if slack_enable == true ~}
slack:
  clientId: "${sentry_slack_client_id}"
  clientSecret: "${sentry_slack_client_secret}"
  signingSecret: "${sentry_slack_signing_secret}"
%{ endif ~}

hooks:
  activeDeadlineSeconds: 600
